Repository codesquad-members-2021/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#1 [TEAM 02] 연 & 시온 - DB설계 및 Entity 구현 리뷰 요청드립니다.
  BE/README.md
  BE/issue_tracker/.gitignore
  BE/issue_tracker/build.gradle
  BE/issue_tracker/gradle/wrapper/gradle-wrapper.jar
  BE/issue_tracker/gradle/wrapper/gradle-wrapper.properties
  BE/issue_tracker/gradlew
  BE/issue_tracker/gradlew.bat
  BE/issue_tracker/settings.gradle
  BE/issue_tracker/src/main/java/team02/issue_tracker/IssueTrackerApplication.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Comment.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/CommentEmoji.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Emoji.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Issue.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/IssueAssignee.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/IssueLabel.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Label.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Milestone.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/User.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/composite_key/CommentEmojiId.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/composite_key/IssueAssigneeId.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/composite_key/IssueLabelId.java
  BE/issue_tracker/src/main/resources/application.properties
  BE/issue_tracker/src/test/java/team02/issue_tracker/IssueTrackerApplicationTests.java
  FE/README.md
  iOS/README.md
Labels: review-BE

#8 [Team-13 / FE ]- Raccoon & Tami Material UI 적용 & Atomic component 구현
  .gitignore
  README.md
  backend/README.md
  frontend/README.md
  frontend/issue-cracker/.eslintrc.js
  frontend/issue-cracker/.gitignore
  frontend/issue-cracker/README.md
  frontend/issue-cracker/package-lock.json
  frontend/issue-cracker/package.json
  frontend/issue-cracker/public/index.html
  frontend/issue-cracker/src/App.tsx
  frontend/issue-cracker/src/components/Callback.tsx
  frontend/issue-cracker/src/components/common/ButtonGroup.tsx
  frontend/issue-cracker/src/components/common/CheckBoxes.tsx
  frontend/issue-cracker/src/components/common/FilterBar.tsx
  frontend/issue-cracker/src/components/common/InputGroup.tsx
  frontend/issue-cracker/src/components/common/IssueCell.tsx
  frontend/issue-cracker/src/components/common/LabelLargeGroup.tsx
  frontend/issue-cracker/src/components/common/LabelSmallGroup.tsx
  frontend/issue-cracker/src/components/common/Logo.tsx
  frontend/issue-cracker/src/components/common/ProfileImg.tsx
  frontend/issue-cracker/src/components/common/ProgrerssBar.tsx
  frontend/issue-cracker/src/components/common/RegisterButton.tsx
  frontend/issue-cracker/src/components/common/TabGroup.tsx
  frontend/issue-cracker/src/components/common/TabList.tsx
  frontend/issue-cracker/src/components/common/TextArea.tsx
  frontend/issue-cracker/src/components/common/TextAreaTest.tsx
  frontend/issue-cracker/src/components/layout/Header/index.tsx
  frontend/issue-cracker/src/components/layout/IssueList/IssueCell.tsx
  frontend/issue-cracker/src/components/layout/IssueList/IssueNav.tsx
  frontend/issue-cracker/src/components/layout/IssueList/IssueTable.tsx
  frontend/issue-cracker/src/components/layout/IssueList/IssueTableHeader.tsx
  frontend/issue-cracker/src/components/layout/IssueList/index.tsx
  frontend/issue-cracker/src/components/layout/Loader/index.tsx
  frontend/issue-cracker/src/components/layout/LogIn/index.tsx
  frontend/issue-cracker/src/components/styles/ButtonStyles.tsx
  frontend/issue-cracker/src/components/styles/CommonStyles.tsx
  frontend/issue-cracker/src/components/styles/GlobalStyle.tsx
  frontend/issue-cracker/src/components/styles/InputStyles.tsx
  frontend/issue-cracker/src/components/styles/svg/AccountIcon.tsx
  frontend/issue-cracker/src/components/styles/svg/IssueClosedIcon.tsx
  frontend/issue-cracker/src/components/styles/svg/IssueOpenIcon.tsx
  frontend/issue-cracker/src/components/styles/theme.ts
  frontend/issue-cracker/src/index.tsx
  frontend/issue-cracker/src/react-app-env.d.ts
  frontend/issue-cracker/src/utils/const.ts
  frontend/issue-cracker/tsconfig.json
  frontend/issue-cracker/yarn.lock
  frontend/package-lock.json
  frontend/package.json
  mobile/README.md
Labels: review-FE

#9 [iOS] StackView에 Subview 동적 할당
  .gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/ray.xcuserdatad/UserInterfaceState.xcuserstate
  IssueTracker/IssueTracker.xcodeproj/xcuserdata/ray.xcuserdatad/xcschemes/xcschememanagement.plist
  IssueTracker/IssueTracker/Assets.xcassets/AccentColor.colorset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/apple.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/apple.imageset/apple.png
  IssueTracker/IssueTracker/Assets.xcassets/apple.png
  IssueTracker/IssueTracker/Assets.xcassets/github.imageset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/github.imageset/github.png
  IssueTracker/IssueTracker/Assets.xcassets/github.png
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/Model/Assignee.swift
  IssueTracker/IssueTracker/Model/FilterList.swift
  IssueTracker/IssueTracker/Model/Issue.swift
  IssueTracker/IssueTracker/Model/Label.swift
  IssueTracker/IssueTracker/Presenter/Controller/FilterIssueViewController.swift
  IssueTracker/IssueTracker/Presenter/Controller/IssueListViewController.swift
  IssueTracker/IssueTracker/Presenter/Controller/LoginViewController.swift
  IssueTracker/IssueTracker/Presenter/Controller/RedirectionViewController.swift
  IssueTracker/IssueTracker/Presenter/Delegate/AppDelegate.swift
  IssueTracker/IssueTracker/Presenter/Delegate/SceneDelegate.swift
  IssueTracker/IssueTracker/Presenter/Supports/Base.lproj/LaunchScreen.storyboard
  IssueTracker/IssueTracker/Presenter/Supports/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Presenter/View/FilterCell.swift
  IssueTracker/IssueTracker/Presenter/View/IssueCell.swift
  IssueTracker/IssueTracker/Presenter/View/LabelView.swift
  IssueTracker/IssueTracker/Service/Constant.swift
  IssueTracker/IssueTracker/Service/IssueDTO.swift
  IssueTracker/IssueTracker/Service/LoginDTO.swift
  IssueTracker/IssueTracker/Service/Network/APIService.swift
  IssueTracker/IssueTracker/Service/Network/LoginManager.swift
  IssueTracker/IssueTracker/UseCase/FilterMemoryStorage.swift
  IssueTracker/IssueTracker/UseCase/IssueMemoryStorage.swift
  IssueTracker/IssueTracker/UseCase/LoginObserver.swift
  IssueTracker/IssueTracker/ViewModel/FilterViewModel.swift
  IssueTracker/IssueTracker/ViewModel/IssueListViewModel.swift
  README.md
Labels: review-iOS

#18 [team-12] Eamon & Autumn 1주차 PR
  fe/.gitignore
  fe/.prettierrc.json
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/components/Issues/IssueItem.tsx
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/Issues/IssueList.tsx
  fe/src/components/Issues/Issues.tsx
  fe/src/components/Issues/IssuesHeader.tsx
  fe/src/components/buttons/GitHubLoginButton.tsx
  fe/src/components/common/AuthorAvatar.tsx
  fe/src/components/common/CommentInput.tsx
  fe/src/components/common/Filter.tsx
  fe/src/components/common/FilterItem.tsx
  fe/src/components/common/FilterList.tsx
  fe/src/components/common/IssueFilter.tsx
  fe/src/components/common/IssueTitleInput.tsx
  fe/src/components/common/Label.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/navbar/Navbar.tsx
  fe/src/components/new-issue/NewIssueLeft.tsx
  fe/src/hook/useAxios.tsx
  fe/src/icons/IconsRefresh.svg
  fe/src/icons/Xicon.svg
  fe/src/icons/arrow-down.svg
  fe/src/icons/check-off-circle.svg
  fe/src/icons/check-on-circle.svg
  fe/src/icons/closeIssue.svg
  fe/src/icons/delete.svg
  fe/src/icons/edit.svg
  fe/src/icons/emoji.svg
  fe/src/icons/file-upload.svg
  fe/src/icons/label.svg
  fe/src/icons/openIssue.svg
  fe/src/icons/openMilestone.svg
  fe/src/icons/pluse.svg
  fe/src/icons/search.svg
  fe/src/index.css
  fe/src/index.tsx
  fe/src/pages/IssuesPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/NewIssuePage.tsx
  fe/src/pages/OAuthPage.tsx
  fe/src/react-app-env.d.ts
  fe/src/setupTests.ts
  fe/src/style/GlobalStyle.tsx
  fe/src/style/commonStyle.ts
  fe/src/style/theme.ts
  fe/src/types/filterType.ts
  fe/src/types/issueType.ts
  fe/tsconfig.json
  fe/yarn.lock
Labels: review-FE

#10 [TEAM06 -FE] :카일&주나미 - 1주차 PR
  .vscode/settings.json
  frontend/.env
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/miles.png
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/atom/CheckBox.tsx
  frontend/src/components/atom/LabelBadge.tsx
  frontend/src/components/atom/LableList.tsx
  frontend/src/components/atom/List.tsx
  frontend/src/components/atom/MilestoneIcon.tsx
  frontend/src/components/atom/PrimaryButton.tsx
  frontend/src/components/atom/ProfileImg.tsx
  frontend/src/components/atom/RadioBtn.tsx
  frontend/src/components/atom/Title.tsx
  frontend/src/components/common/Copyright.tsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/components/common/LabelSelectItem.tsx
  frontend/src/components/common/MilestoneSelectItem.tsx
  frontend/src/components/common/UserSelectItem.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/hooks/useToggle.tsx
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/loginPage/loginForm/LoginForm.tsx
  frontend/src/page/loginPage/loginLogo/LoginLogo.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/page/mainPage/issueTable/IssueTable.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeader.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderLeft.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderRight.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/IssueTableFilterModal.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/ModalContentList.tsx
  frontend/src/page/mainPage/issueTable/issueType.tsx
  frontend/src/page/mainPage/optionTable/OptionTable.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilter.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterBtn.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/SearchInput.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/store/issueInfoStore.ts
  frontend/src/style/Theme.tsx
  frontend/src/util/util.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: review-FE

#13 [Team-03 iOS Hong, ZG] View, Entity 규정
  .gitignore
  .gitignore~Stashed changes
  iOS/issueTracker/.swiftlint.yml
  iOS/issueTracker/Podfile
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/Podfile.lock~Stashed changes
  iOS/issueTracker/Podfile~Stashed changes
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj~Stashed changes
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTracker.xcscheme
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTrackerTests.xcscheme
  iOS/issueTracker/issueTracker/AppDelegate.swift
  iOS/issueTracker/issueTracker/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/filterIcon.imageset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/filterIcon.imageset/filterIcon.png
  iOS/issueTracker/issueTracker/Assets.xcassets/milestoneIcon.imageset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/milestoneIcon.imageset/milestoneIcon.png
  iOS/issueTracker/issueTracker/Assets.xcassets/selectIcon.imageset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/selectIcon.imageset/selectIcon.png
  iOS/issueTracker/issueTracker/Base.lproj/LaunchScreen.storyboard
  iOS/issueTracker/issueTracker/Controller/IssueFilterViewController.swift
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LoginViewController.swift
  iOS/issueTracker/issueTracker/Controller/NewIssueViewController.swift
  iOS/issueTracker/issueTracker/Entity/Comment.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/Issue.swift
  iOS/issueTracker/issueTracker/Entity/IssueCount.swift
  iOS/issueTracker/issueTracker/Entity/Issues.swift
  iOS/issueTracker/issueTracker/Entity/Label.swift
  iOS/issueTracker/issueTracker/Entity/Milestone.swift
  iOS/issueTracker/issueTracker/Entity/Rooms.swift
  iOS/issueTracker/issueTracker/Entity/SendIssue.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
  iOS/issueTracker/issueTracker/Identity/StoryBoardIdentity.swift
  iOS/issueTracker/issueTracker/Info.plist
  iOS/issueTracker/issueTracker/Network/EndPoint.swift
  iOS/issueTracker/issueTracker/Network/NetworkManager.swift
  iOS/issueTracker/issueTracker/SceneDelegate.swift
  iOS/issueTracker/issueTracker/StoryBoard/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/Label.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/MileStone.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/MyAccount.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/NewIssue.storyboard
  iOS/issueTracker/issueTracker/View/CustomSectionHeader.swift
  iOS/issueTracker/issueTracker/View/HeaderView.swift
  iOS/issueTracker/issueTracker/View/IssueTableViewCell.swift
  iOS/issueTracker/issueTracker/View/filterOptionCell.swift
  iOS/issueTracker/issueTrackerTests/Info.plist
  iOS/issueTracker/issueTrackerTests/issueTrackerTests.swift
Labels: review-iOS

#15 [Be] team04 mockup-api 완성
  .github/workflows/heroku.yml
  .gitignore
  Procfile
  be/issue-tracker-be/.gitignore
  be/issue-tracker-be/build.gradle
  be/issue-tracker-be/gradle/wrapper/gradle-wrapper.jar
  be/issue-tracker-be/gradle/wrapper/gradle-wrapper.properties
  be/issue-tracker-be/gradlew
  be/issue-tracker-be/gradlew.bat
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/IssueTrackerBeApplication.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/dto/CommentResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/vo/Emoji.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/comment/vo/Emojis.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/controller/CommonExceptionHandler.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/common/dto/ErrorResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/controller/FileController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/controller/FileDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/controller/MultipartFileNotFoundException.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/dto/FileResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/file/dto/FileResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueDetailResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueDetailResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/dto/IssueStateRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/controller/LabelController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/controller/LabelDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelsCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/label/dto/LabelsCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/controller/MilestoneController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/controller/MilestoneDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestoneResponses.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestonesCountResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/milestone/dto/MilestonesCountResponseWrapper.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/controller/UserController.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/controller/UserDummyData.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/dto/UserResponse.java
  be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/user/dto/UserResponses.java
  be/issue-tracker-be/src/main/resources/application.properties
  be/issue-tracker-be/src/main/resources/static/images/AI7.png
  be/issue-tracker-be/src/main/resources/static/images/소라게.jpg
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: review-BE

#24 [Team10 BE 새리] OAuth 구현
  BE/issuetracker/.gitignore
  BE/issuetracker/build.gradle
  BE/issuetracker/gradle/wrapper/gradle-wrapper.jar
  BE/issuetracker/gradle/wrapper/gradle-wrapper.properties
  BE/issuetracker/gradlew
  BE/issuetracker/gradlew.bat
  BE/issuetracker/settings.gradle
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/IssuetrackerApplication.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/config/InterceptorConfig.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/controller/UserController.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/domain/User.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/ApiResult.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/GithubTokenDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/GithubUserInfoDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/GoogleTokenDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/GoogleUserInfoDTO.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/dto/UserInfo.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/exception/AuthorizationNotFoundException.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/exception/InvalidAccessTokenException.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/exception/TokenNotValidException.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/exception/UserNotFoundException.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/interceptor/LoginInterceptor.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/repository/UserRepository.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/GithubOauthService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/GoogleOauthService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/OauthService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/service/UserService.java
  BE/issuetracker/src/main/java/com/codesquad/issuetracker/utils/JwtUtil.java
  BE/issuetracker/src/main/resources/application-test.properties
  BE/issuetracker/src/main/resources/application.properties
  BE/issuetracker/src/test/java/com/codesquad/issuetracker/IssuetrackerApplicationTests.java
  BE/issuetracker/src/test/java/com/codesquad/issuetracker/service/UserServiceTest.java
Labels: review-BE

#6 [iOS][Team-04 Dumba & Lia] 이슈 목록 화면 구현
  ios/.gitignore
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/IssueTracker/IssueTracker/Application/AppDelegate.swift
  ios/IssueTracker/IssueTracker/Application/DIContainer/IssueTrackerDIContainer.swift
  ios/IssueTracker/IssueTracker/Application/Flow/SceneFlowCoordinator.swift
  ios/IssueTracker/IssueTracker/Application/SceneDelegate.swift
  ios/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  ios/IssueTracker/IssueTracker/IssueList/Model/Issue.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/IssueListMockData.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Label.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/Milestone.swift
  ios/IssueTracker/IssueTracker/IssueList/Model/User.swift
  ios/IssueTracker/IssueTracker/IssueList/UseCase/FetchIssueListUseCase.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UIBarButtonItem+setTitle.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UIColor+hexToUIColor.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UILabel+AddLineSpacing.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UINibCreatable.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/UIView+HiddenWithAnimation.swift
  ios/IssueTracker/IssueTracker/IssueList/Utility/ViewControllerIdentifierable.swift
  ios/IssueTracker/IssueTracker/IssueList/View/IssueCell.swift
  ios/IssueTracker/IssueTracker/IssueList/View/IssueCell.xib
  ios/IssueTracker/IssueTracker/IssueList/View/IssueLabel.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueDataSource.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewController/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/IssueList/ViewModel/IssueViewModel.swift
  ios/IssueTracker/IssueTracker/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/IssueTracker/IssueTracker/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/IssueTracker/IssueTracker/SupportingFiles/Assets.xcassets/Contents.json
  ios/IssueTracker/IssueTracker/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  ios/IssueTracker/IssueTracker/SupportingFiles/Info.plist
  ios/IssueTracker/IssueTrackerTests/Info.plist
  ios/IssueTracker/IssueTrackerTests/IssueTrackerTests.swift
  ios/IssueTracker/IssueTrackerUITests/Info.plist
  ios/IssueTracker/IssueTrackerUITests/IssueTrackerUITests.swift
  ios/IssueTracker/IssueViewModelTests/Info.plist
  ios/IssueTracker/IssueViewModelTests/IssueViewModelTests.swift
  ios/IssueTracker/UtilityTests/Info.plist
  ios/IssueTracker/UtilityTests/UtilityTests.swift
Labels: review-iOS

#21 [Team1][iOS] 로그인 기능 및 메인 화면 구현
  .gitignore
  BE/README.md
  BE/project_root_here
  FE/README.md
  FE/project_root_here
  README.md
  iOS/README.md
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/issue-tracker/issue-tracker/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/BackGround.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Border.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/CloseCarrot.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/DeleteSunnyside.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/MainGrape.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/OpenBrocoli.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_apple.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_apple.imageset/icon_apple.png
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_github.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_github.imageset/icon_github.png
  iOS/issue-tracker/issue-tracker/Base.lproj/LaunchScreen.storyboard
  iOS/issue-tracker/issue-tracker/Base.lproj/Main.storyboard
  iOS/issue-tracker/issue-tracker/Common/AlertFactory.swift
  iOS/issue-tracker/issue-tracker/Common/Colors.swift
  iOS/issue-tracker/issue-tracker/Common/UIImageExtension.swift
  iOS/issue-tracker/issue-tracker/Common/UIViewControllerExtension.swift
  iOS/issue-tracker/issue-tracker/Info.plist
  iOS/issue-tracker/issue-tracker/LifeCycle/AppDelegate.swift
  iOS/issue-tracker/issue-tracker/LifeCycle/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Apple/AppleAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/GithubAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/OAuthResponseDTO.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginError.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginInfo.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginKeyChainManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginService.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Protocol/SocialLoginManagable.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Protocol/SocialLoginManagerDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/LoginInfoContainer.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarCreator.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/TabBarChildInfo.swift
  iOS/issue-tracker/issue-tracker/Network/ImageLoadManager.swift
  iOS/issue-tracker/issue-tracker/Network/NetworkManager.swift
  iOS/issue-tracker/issue-tracker/issue-tracker.entitlements
  iOS/project_root_here
Labels: review-iOS

#23 [TEAM-11] [FE] Rano & json : 첫번째 PR
  FE/.gitignore
  FE/.prettierrc
  FE/craco.config.js
  FE/package.json
  FE/public/image/profile.png
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/Common/BackgroundFluid.tsx
  FE/src/components/Common/CircleCheckBox.tsx
  FE/src/components/Common/DefaultButton.tsx
  FE/src/components/Common/DefaultInput.tsx
  FE/src/components/Common/Icons.tsx
  FE/src/components/Common/Label.tsx
  FE/src/components/Common/ListModal.tsx
  FE/src/components/Common/LoadingSpinner.tsx
  FE/src/components/Common/Modal.tsx
  FE/src/components/Common/PrimaryButton.tsx
  FE/src/components/Header/Logo.tsx
  FE/src/components/Header/UserMenu.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/ListTable/ListBody.tsx
  FE/src/components/IssueList/ListTable/ListHead.tsx
  FE/src/components/IssueList/ListTable/index.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/NavFilter/TabBar/AddButton.tsx
  FE/src/components/IssueList/NavFilter/TabBar/Tabs.tsx
  FE/src/components/IssueList/NavFilter/TabBar/index.tsx
  FE/src/components/IssueList/NavFilter/index.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/components/LabelList/LabelEdit.tsx
  FE/src/index.css
  FE/src/index.tsx
  FE/src/pages/IssuePage.tsx
  FE/src/pages/IssueWritePage.tsx
  FE/src/pages/LabelListPage.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/RegisterPage.tsx
  FE/src/pages/index.tsx
  FE/src/react-app-env.d.ts
  FE/src/util/API.ts
  FE/src/util/hooks/useFetch.tsx
  FE/src/util/reference.ts
  FE/src/util/store/index.tsx
  FE/src/util/store/issueList.tsx
  FE/src/util/styles/CommonStyledCSS.tsx
  FE/src/util/styles/GlobalStyle.tsx
  FE/src/util/styles/theme/index.ts
  FE/src/util/styles/theme/styled.d.ts
  FE/src/util/types/api.ts
  FE/src/util/types/index.ts
  FE/src/util/types/normal.ts
  FE/src/util/util.ts
  FE/tsconfig.json
  FE/tsconfig.paths.json
  README.md
Labels: review-FE

#36 [Team09 - 디코 빰빰] issue-tracker 2주차 PR 01
  frontend/README.md
  frontend/package.json
  frontend/public/mockData.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/IssueCategoryFilter/IssueCategoryFilter.tsx
  frontend/src/components/IssueList/IssueList.tsx
  frontend/src/components/LoginButton.tsx
  frontend/src/components/SignIn/GithubLogin.tsx
  frontend/src/components/SignIn/IDLogin.tsx
  frontend/src/components/SignIn/SignInButton.tsx
  frontend/src/components/SignIn/index.tsx
  frontend/src/components/common/DropDown.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/Label.tsx
  frontend/src/components/common/ResponsiveLayout.tsx
  frontend/src/components/common/icons/ArrowIcon.tsx
  frontend/src/components/common/icons/Close.tsx
  frontend/src/components/common/icons/Plus.tsx
  frontend/src/components/common/icons/index.tsx
  frontend/src/lib/API/API.js
  frontend/src/lib/MyRecoil/MyRecoil.tsx
  frontend/src/lib/MyUseCallback.tsx/MyUseCallback.tsx
  frontend/src/pages/AddIssuePage.tsx
  frontend/src/pages/IssueListPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/OAuthCallbackPage.tsx
  frontend/src/pages/SigninPage.tsx
  frontend/tsconfig.json
Labels: review-FE

#42 [TEAM - 02] 연과 시온 : QueryDSL을 이용한 이슈 필터링 조회 & WebFlux를 이용한 소셜 로그인
  BE/issue_tracker/.gitignore
  BE/issue_tracker/build.gradle
  BE/issue_tracker/src/main/java/team02/issue_tracker/config/AopConfig.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/config/QuerydslConfig.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/config/SwaggerConfig.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/config/WebMvcConfig.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/controller/CommentController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/controller/CommonController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/controller/IssueController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/controller/LabelController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/controller/MilestoneController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/controller/UserController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Filter.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/Issue.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/domain/User.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/dto/issue/AbstractIssueResponse.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/dto/issue/IssueCommentResponse.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/dto/issue/IssueResponse.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/exception_handler/GlobalExceptionHandler.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/filter/CorsFilter.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/controller/OAuthController.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/AccessToken.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/AccessTokenRequest.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/GithubAccessTokenResponseDto.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/JwtResponse.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/SocialLogin.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/github/GithubAccessToken.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/github/GithubAccessTokenRequest.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/github/GithubUserProfile.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/google/GoogleAccessToken.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/google/GoogleUserProfile.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/kakao/KakaoAccessToken.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/kakao/KakaoUserProfile.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/naver/NaverAccessToken.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/dto/naver/NaverUserProfile.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/exception/IncorrectTokenTypeException.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/exception/InvalidAccessTokenRequestException.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/exception/InvalidTokenTypeException.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/exception/InvalidUserRequestException.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/jwt/JwtFactory.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/jwt/JwtFinder.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/service/GithubLoginService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/service/GoogleLoginService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/service/KakaoLoginService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/service/LoginService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/service/NaverLoginService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/service/OAuthService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/oauth/utils/GithubApiProperties.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/repository/CommentRepository.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/repository/IssueSearchRepository.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/service/CommentService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/service/IssueService.java
  BE/issue_tracker/src/main/java/team02/issue_tracker/service/UserService.java
  BE/issue_tracker/src/main/resources/application.properties
  BE/issue_tracker/src/main/resources/data.sql
  BE/issue_tracker/src/test/java/team02/issue_tracker/IssueSearchRepositoryTest.java
  BE/issue_tracker/src/test/java/team02/issue_tracker/oauth/service/GithubLoginServiceTest.java
Labels: review-BE

#25 [Team-13 iOS Neo] 로그인 UI 및 로직
  mobile/.gitignore
  mobile/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  mobile/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  mobile/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mobile/issue-tracker/issue-tracker/AppCycle/AppDelegate.swift
  mobile/issue-tracker/issue-tracker/AppCycle/SceneDelegate.swift
  mobile/issue-tracker/issue-tracker/AppDelegate.swift
  mobile/issue-tracker/issue-tracker/Assets.xcassets/AccentColor.colorset/Contents.json
  mobile/issue-tracker/issue-tracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  mobile/issue-tracker/issue-tracker/Assets.xcassets/Contents.json
  mobile/issue-tracker/issue-tracker/Assets.xcassets/github_icon.imageset/Contents.json
  mobile/issue-tracker/issue-tracker/Assets.xcassets/github_icon.imageset/github_icon.png
  mobile/issue-tracker/issue-tracker/Assets.xcassets/github_icon.imageset/github_icon@2x.png
  mobile/issue-tracker/issue-tracker/Assets.xcassets/github_icon.imageset/github_icon@3x.png
  mobile/issue-tracker/issue-tracker/Base.lproj/LaunchScreen.storyboard
  mobile/issue-tracker/issue-tracker/DataLayer/Model/Auth.swift
  mobile/issue-tracker/issue-tracker/DataLayer/Network/Endpoint.swift
  mobile/issue-tracker/issue-tracker/DataLayer/Network/Error.swift
  mobile/issue-tracker/issue-tracker/DataLayer/Network/Method.swift
  mobile/issue-tracker/issue-tracker/DataLayer/Network/URLRouter.swift
  mobile/issue-tracker/issue-tracker/DataLayer/Repository.swift
  mobile/issue-tracker/issue-tracker/DomainLayer/LoginService.swift
  mobile/issue-tracker/issue-tracker/Extension/Encodable+Extension.swift
  mobile/issue-tracker/issue-tracker/Extension/UIAlertController+Extension.swift
  mobile/issue-tracker/issue-tracker/Extension/UIStoryBoard+Extension.swift
  mobile/issue-tracker/issue-tracker/Info.plist
  mobile/issue-tracker/issue-tracker/PresentationLayer/IntialViewController.swift
  mobile/issue-tracker/issue-tracker/PresentationLayer/Login/Login.storyboard
  mobile/issue-tracker/issue-tracker/PresentationLayer/Login/LoginViewController.swift
  mobile/issue-tracker/issue-tracker/PresentationLayer/Login/LoginViewModel.swift
  mobile/issue-tracker/issue-tracker/PresentationLayer/New Group/Base.lproj/Main.storyboard
  mobile/issue-tracker/issue-tracker/PresentationLayer/New Group/MainViewController.swift
  mobile/issue-tracker/issue-tracker/SceneDelegate.swift
  mobile/issue-tracker/issue-tracker/Utility/ASWebAuthPublisher.swift
  mobile/issue-tracker/issue-tracker/ViewController.swift
  mobile/issue-tracker/issue-trackerTests/EndPointTests.swift
  mobile/issue-tracker/issue-trackerTests/GithubConfigurationTests.swift
  mobile/issue-tracker/issue-trackerTests/Info.plist
  mobile/issue-tracker/issue-trackerTests/MockRepository.swift
  mobile/issue-tracker/issue-trackerTests/RepositoryTests.swift
  mobile/issue-tracker/issue-trackerUITests/Info.plist
  mobile/issue-tracker/issue-trackerUITests/LoginUITests.swift
  mobile/issue-tracker/issue-trackerUITests/LoginUITests2.swift
Labels: review-iOS
